### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Anton-V-K** [wxIshiko/wxCharts#110] opened 2019-05-27 21:31 UTC
I tried two samples (`WxLine` and `WxCandlestick`) with wxWidgets-3.1.2 (VS2017). They both work fine, except for a lot of memory leaks which are dumped into Output window when running an application in Visual Studio.
It is not a big issue for a sample application, but in the real long-running application it may reveal a serious problem.
During quick debug session I wasn't able to discover whether the leaks are causes by incorrectly written sample, or they are hiding in wxCharts objects, so this should be further investigated.

**Comment by Kvaz1r** [comment] 2019-05-28 14:47
It's indeed a bug in wxCharts and not in the samples. Can you make destructor virtual for  [wxChartTooltipProvider](https://github.com/wxIshiko/wxCharts/blob/master/include/wx/charts/wxcharttooltipprovider.h#L33) and check again? I can't reproduce memory leak after that.

**Comment by Anton-V-K** [comment] 2019-05-29 09:35
Thanks for the reply.
Adding virtual dtor indeed solves a lot of mem leaks, when running WxLine sample.
WxCandlestick sample still generates a lot of mem leaks, so I guess another abstract class without a virtual dtor is hanging around somethere.

**Comment by Kvaz1r** [comment] 2019-05-29 11:15
I don't think so because [Dr. Memory](http://drmemory.org) can't find unreachable leaks in WxCandlestick sample. 

> [Memory that is still reachable by the application. This is NOT considered a leak. It is reported as "still-reachable allocation(s)" in Dr. Memory's summary. Many applications do not explicitly free memory whose lifetime matches the process lifetime and this is not considered an error by Dr. Memory.](http://drmemory.org/docs/page_leaks.html)

Are Visual Studio detect memory leaks for samples for wxWidgets itself? Some of them can be false positives because wxWidgets take care about widget memory allocations.

**Comment by Anton-V-K** [comment] 2019-05-29 15:27
@Kvaz1r , you're right - there are no other memory leaks. I've rebuilt the library and the samples, and all leaks seem to be gone :)

**Comment by xleclercq** [comment] 2019-05-29 19:54
If there are no other leaks it's good. But one other area where I had some concerns is shared pointer circular references. We do use them heavily and it's something I need to check.

**Comment by xleclercq** [comment] 2019-06-01 14:09
Fixed in 7ea48abcc14c10d7807233a7e4aaeab8ccaddc18

**Closed by xleclercq** 2019-06-01 14:09 UTC
